package com.groupware.griphook.domain.enumeration;

/**
 * The GW_SKU enumeration.
 */
public enum GW_SKU {
    GW_PS_VIRT, GW_PS_SYSTEMS, GW_PS_STORAGE, GW_PS_SEC, GW_PS_PROJMNGMT, GW_PS_PC, GW_PS_NETWORK, GW_PS_MS, GW_PS_MOBILITY, GW_PS_INT_FLD, GW_PS_COLLAB, GW_PS_CLOUD, GW_PS_APPS, GW_PS_AI, GW_CONSULTING_VIRT, GW_CONSULTING_STORAGE, GW_CONSULTING_SEC, GW_CONSULTING_NET, GW_CONSULTING_MS, GW_CONSULTING_COLLAB, GW_CONSULTING_CLD, GW_CONSULTING_AI
}
